services:
  db:
    container_name: hof-or-not-service-db
    image: cimg/postgres:14.4
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db/player-picture-base64s.csv:/app/player-picture-base64s.csv
    healthcheck:
      test: "pg_isready -q -U ${POSTGRES_USER}"
  flyway:
    container_name: flyway
    image: flyway/flyway
    entrypoint: sh
    command:
      -c "
      flyway -url=jdbc:postgresql://db/${POSTGRES_DB} -schemas=${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -locations=filesystem:/flyway/sql migrate"
    volumes:
      - ${PWD}/db/migration:/flyway/sql
    depends_on:
      db:
        condition: service_healthy